name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.2.0'
            use-public-rspm: true
 
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: false
      
      - name: Render Quarto Project
        shell: bash
        run: |
          quarto render index.qmd --output-dir _site
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: _site
          SINGLE_COMMIT: true
